llm:
  default_model_type: fast
  max_cost: 10.0
  min_performance: 0.7
  min_quality: 0.8
  optimization_goal: cost
  providers:
    gemini:
      api_key: AIzaSyA5ZvFnNDMWiFNWe3aElZDmi8V5UMTEKEk
      max_retries: 3
      models:
        gemini-1.5-flash:
          capabilities:
          - text
          - json
          cost_per_1k_tokens: 7.5e-05
          max_tokens: 1000000
          model_type: fast
          name: gemini-1.5-flash
      provider: gemini
      timeout: 30
logging:
  format: detailed
  level: DEBUG
monitoring:
  alert_thresholds:
    max_cost_per_hour: 5.0
    max_latency_ms: 5000
    success_rate: 0.95
  retention_hours: 24
