# gemini_sre_agent/llm/constants.py

"""
Constants for LLM operations and configurations.
"""

# Timeout constants
DEFAULT_TIMEOUT_SECONDS = 30
HEALTH_CHECK_TIMEOUT_SECONDS = 10
CACHE_TTL_SECONDS = 3600

# Resource limits
MAX_CONCURRENT_REQUESTS = 5
MAX_PROMPT_LENGTH = 50000
MAX_MODEL_CONFIGS = 10
MAX_CONTEXT_SIZE = 10000
MAX_LATENCY_SAMPLES = 1000

# Cost and performance thresholds
DEFAULT_COST_THRESHOLD = 1.0
ERROR_RATE_THRESHOLD = 0.1
COST_OPTIMIZATION_THRESHOLD = 0.8

# Retry configuration
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY_SECONDS = 1.0
MAX_RETRY_DELAY_SECONDS = 60.0

# Monitoring and metrics
METRICS_RETENTION_HOURS = 24
HEALTH_CHECK_INTERVAL_SECONDS = 30
DASHBOARD_PORT = 8080
DASHBOARD_HOST = "localhost"

# Security settings
RATE_LIMIT_PER_MINUTE = 100
MAX_REQUEST_SIZE_BYTES = 1024 * 1024  # 1MB

# Model mixing weights
DEFAULT_PERFORMANCE_WEIGHT = 0.4
DEFAULT_COST_WEIGHT = 0.3
DEFAULT_QUALITY_WEIGHT = 0.3

# Logging
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FORMAT = "json"

# Provider-specific limits
OPENAI_MAX_TOKENS = 4096
ANTHROPIC_MAX_TOKENS = 4096
GOOGLE_MAX_TOKENS = 4096

# Task decomposition
MAX_SUBTASKS = 10
MIN_SUBTASK_LENGTH = 10
MAX_SUBTASK_LENGTH = 1000

# Result aggregation
MAX_AGGREGATION_ATTEMPTS = 3
AGGREGATION_TIMEOUT_SECONDS = 60

# Context sharing
MAX_CONTEXT_ENTRIES = 100
CONTEXT_TTL_SECONDS = 1800  # 30 minutes

# Error handling
MAX_ERROR_MESSAGE_LENGTH = 1000
ERROR_RETRY_BACKOFF_FACTOR = 2.0

# Performance monitoring
LATENCY_PERCENTILES = [50, 95, 99]
PERFORMANCE_WINDOW_SIZE = 100

# Cost tracking
COST_PRECISION_DECIMALS = 6
BUDGET_ALERT_THRESHOLD = 0.8  # Alert when 80% of budget is used

# Health check thresholds
HEALTHY_RESPONSE_TIME_MS = 5000
HEALTHY_SUCCESS_RATE = 0.95
HEALTHY_ERROR_RATE = 0.05

# Model selection
MIN_MODEL_CONFIDENCE = 0.7
MAX_MODEL_SELECTION_ATTEMPTS = 3

# Caching
CACHE_KEY_PREFIX = "llm_cache"
CACHE_VERSION = "1.0"

# API endpoints
HEALTH_ENDPOINT = "/health"
METRICS_ENDPOINT = "/metrics"
DASHBOARD_ENDPOINT = "/dashboard"
API_VERSION = "v1"

# File and data limits
MAX_CONFIG_FILE_SIZE = 1024 * 1024  # 1MB
MAX_LOG_FILE_SIZE = 100 * 1024 * 1024  # 100MB
MAX_BACKUP_FILES = 10

# Network settings
DEFAULT_CONNECTION_TIMEOUT = 30
DEFAULT_READ_TIMEOUT = 60
MAX_CONNECTIONS_PER_HOST = 10

# Validation patterns
VALID_PROVIDER_NAMES = ["openai", "anthropic", "google", "claude", "gemini"]
VALID_MODEL_TYPES = ["smart", "fast", "creative", "analytical"]
VALID_TASK_TYPES = [
    "text_generation",
    "code_generation",
    "data_processing",
    "creative_writing",
    "analysis",
    "translation",
    "summarization",
]

# Environment variables
ENV_PREFIX = "GEMINI_SRE_AGENT_"
CONFIG_FILE_ENV = f"{ENV_PREFIX}CONFIG_FILE"
LOG_LEVEL_ENV = f"{ENV_PREFIX}LOG_LEVEL"
DEBUG_ENV = f"{ENV_PREFIX}DEBUG"
